sibling of bbf3b20fc3042950476a51ecdffa0a26862a72b6

diff --git a/script/bundle-linux b/script/bundle-linux
--- a/script/bundle-linux
+++ b/script/bundle-linux
@@ -87,11 +87,7 @@ fi
 
 # Ensure that remote_server does not depend on libssl nor libcrypto, as we got rid of these deps.
 if ldd "${target_dir}/${remote_server_triple}/release/remote_server" | grep -q 'libcrypto\|libssl'; then
-    if [[ "$remote_server_triple" == *-musl ]]; then
-        echo "Error: remote_server still depends on libssl or libcrypto" && exit 1
-    else
-        echo "Info: Using non-musl remote-server build."
-    fi
+    echo "Error: remote_server still depends on libssl or libcrypto" && exit 1
 fi
 
 suffix=""
